### ISSUE TITLE
$ break everything

### ISSUE THREAD

**Issue by githubnemo** [x3ro/merkderwn#2]
Used this test:

```
func TestInlineIndexError(t *testing.T) {
	c := getTestConverter("$5")
	s := string(c.Convert())
	assert.Equal(t, "$5", s)
}
```

Got:

```
--- FAIL: TestInlineIndexError (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 13 [running]:
testing.func·006()
	/home/nemo/.local/go/src/testing/testing.go:441 +0x181
merkdern/merkderwn.(*Converter).handleInlineMath(0xc20803d140, 0x0)
	/home/nemo/Code/go/src/merkdern/merkderwn/main.go:211 +0x552
merkdern/merkderwn.(*Converter).Convert(0xc20803d140, 0x0, 0x0, 0x0)
	/home/nemo/Code/go/src/merkdern/merkderwn/main.go:233 +0xef
merkdern/merkderwn.TestInlineIndexError(0xc20806a360)
	/home/nemo/Code/go/src/merkdern/merkderwn/main_test.go:99 +0xa0
testing.tRunner(0xc20806a360, 0x8a0738)
	/home/nemo/.local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/home/nemo/.local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x7aeef8, 0x8a06c0, 0x6, 0x6, 0x64a401)
	/home/nemo/.local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802e2d0, 0x8ab640)
	/home/nemo/.local/go/src/testing/testing.go:485 +0x6c
main.main()
	merkdern/merkderwn/_test/_testmain.go:62 +0x1d5
exit status 2
FAIL	merkdern/merkderwn	0.137s
```

**Comment by x3ro** [comment]
> du solltest eventuell in den test einbauen dass sachen wie 5$ oder US$ 5 noch funktionieren
